'use client';

// Round 181: Download Manifest + Roomlist PDF (client-side via jsPDF)
// Path: components/visa/VisaPDFDownloads.jsx
//
// USAGE di /visa/[tripId]/page.jsx:
//   import VisaPDFDownloads from '@/components/visa/VisaPDFDownloads';
//   <VisaPDFDownloads trip={trip} passengers={passengersWithCustomers} />

import { useState } from 'react';
import { generateRoomlist, normalizeGender } from '@/lib/utils/roomlist';

function fmtDateID(d) {
  if (!d) return '-';
  const dt = new Date(d);
  if (isNaN(dt)) return d;
  return dt.toLocaleDateString('id-ID', { day: '2-digit', month: 'short', year: 'numeric' });
}

async function loadJsPDF() {
  if (typeof window === 'undefined') return null;
  if (window.jspdf && window.jspdf.jsPDF) return window.jspdf;
  await new Promise((resolve, reject) => {
    const s = document.createElement('script');
    s.src = 'https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.5.1/jspdf.umd.min.js';
    s.onload = resolve;
    s.onerror = reject;
    document.head.appendChild(s);
  });
  await new Promise((resolve, reject) => {
    const s = document.createElement('script');
    s.src = 'https://cdnjs.cloudflare.com/ajax/libs/jspdf-autotable/3.8.2/jspdf.plugin.autotable.min.js';
    s.onload = resolve;
    s.onerror = reject;
    document.head.appendChild(s);
  });
  return window.jspdf;
}

function getPaxRows(passengers) {
  return (passengers || []).map((p) => {
    const c = p.customers || {};
    return {
      name: c.name || '-',
      passport: c.passport_no || c.passport_number || '-',
      passport_expired: c.passport_expiry || c.passport_expired || c.passport_expired_at || null,
      issue_date: c.passport_issued_date || c.issue_date || c.passport_issue_date || null,
      issuing_place: c.passport_issued_at || c.issuing_office || c.place_of_issue || '-',
      // Kolom kembar: data manual tersimpan di birthday/city, auto-scan di dob/place_of_birth.
      // Baca keduanya supaya manifest tidak kosong.
      birth_date: c.birthday || c.dob || c.birth_date || c.date_of_birth || null,
      birth_place: c.place_of_birth || c.city || c.birth_place || '-',
      nik: c.nik || c.ktp_number || '-',
      phone: c.phone || c.whatsapp || '-',
      email: c.email || '-',
      address: c.ktp_alamat || c.address || '-',
      gender: c.gender || c.sex || '-',
      room_type: p.room_type || '-',
      room_mate: p.room_mate || p.roommate || '-',
      notes: p.notes || '',
    };
  });
}

function setHeader(doc, title, trip) {
  const w = doc.internal.pageSize.getWidth();
  doc.setFillColor(99, 102, 241); // indigo
  doc.rect(0, 0, w, 18, 'F');
  doc.setTextColor(255);
  doc.setFontSize(14);
  doc.setFont(undefined, 'bold');
  doc.text('TEONE — TRAVELING EROPA', 14, 9);
  doc.setFontSize(9);
  doc.setFont(undefined, 'normal');
  doc.text(title, w - 14, 9, { align: 'right' });
  doc.setFontSize(8);
  doc.text(`Generated: ${new Date().toLocaleString('id-ID')}`, w - 14, 14, { align: 'right' });
  doc.setTextColor(30);
}

function setFooter(doc) {
  const pages = doc.internal.getNumberOfPages();
  for (let i = 1; i <= pages; i++) {
    doc.setPage(i);
    const w = doc.internal.pageSize.getWidth();
    const h = doc.internal.pageSize.getHeight();
    doc.setFontSize(8);
    doc.setTextColor(120);
    doc.text(`Page ${i} / ${pages}`, w - 14, h - 6, { align: 'right' });
    doc.text('Generated by TEONE — Traveling Eropa', 14, h - 6);
  }
}

export default function VisaPDFDownloads({ trip, passengers = [] }) {
  const [pending, setPending] = useState(null); // 'manifest' | 'roomlist' | null
  const [error, setError] = useState('');

  const tripLabel = trip?.kode_trip || trip?.id || 'trip';
  const tripName = trip?.name || '';
  const departure = trip?.departure;
  const arrival = trip?.arrival || trip?.return_date;

  async function downloadManifest() {
    setPending('manifest');
    setError('');
    try {
      const jspdf = await loadJsPDF();
      if (!jspdf) throw new Error('jsPDF gak ke-load');
      const { jsPDF } = jspdf;
      const doc = new jsPDF({ unit: 'mm', format: 'a4', orientation: 'landscape' });
      const w = doc.internal.pageSize.getWidth();
      const rows = getPaxRows(passengers);

      setHeader(doc, 'MANIFEST PESERTA', trip);

      // Trip info
      let y = 26;
      doc.setFontSize(16);
      doc.setFont(undefined, 'bold');
      doc.text(`${tripName}`, 14, y);
      y += 6;
      doc.setFontSize(10);
      doc.setFont(undefined, 'normal');
      doc.text(`Kode: ${tripLabel}  ·  Berangkat: ${fmtDateID(departure)}${arrival ? `  ·  Pulang: ${fmtDateID(arrival)}` : ''}`, 14, y);
      y += 4;
      doc.text(`Total peserta: ${rows.length} orang`, 14, y);
      y += 4;

      // Table — semua kolom paspor lengkap. NIK & Alamat KTP muncul otomatis kalau ada
      // data NIK (khusus Khasanah); kolom lain tampil utk kedua brand.
      const hasKtp = rows.some((r) => r.nik && r.nik !== '-');
      const headers = [['#', 'Nama Lengkap', 'Gender', 'No. Passport', 'Tgl Issue', 'Issuing Place', 'Berlaku Sampai', 'Tgl Lahir', 'Tempat Lahir', ...(hasKtp ? ['NIK', 'Alamat KTP'] : []), 'Phone']];
      const tableRows = rows.map((r, idx) => [
        idx + 1,
        r.name,
        r.gender === 'male' ? 'L' : r.gender === 'female' ? 'P' : r.gender,
        r.passport,
        fmtDateID(r.issue_date),
        r.issuing_place,
        fmtDateID(r.passport_expired),
        fmtDateID(r.birth_date),
        r.birth_place,
        ...(hasKtp ? [r.nik, r.address || '-'] : []),
        r.phone,
      ]);

      const colStyles = hasKtp
        ? { 0: { cellWidth: 7 }, 1: { cellWidth: 30 }, 2: { cellWidth: 9 }, 3: { cellWidth: 20 }, 4: { cellWidth: 17 }, 5: { cellWidth: 24 }, 6: { cellWidth: 17 }, 7: { cellWidth: 17 }, 8: { cellWidth: 20 }, 9: { cellWidth: 28 }, 10: { cellWidth: 38 }, 11: { cellWidth: 22 } }
        : { 0: { cellWidth: 7 }, 1: { cellWidth: 34 }, 2: { cellWidth: 9 }, 3: { cellWidth: 22 }, 4: { cellWidth: 18 }, 5: { cellWidth: 26 }, 6: { cellWidth: 18 }, 7: { cellWidth: 18 }, 8: { cellWidth: 22 }, 9: { cellWidth: 26 } };

      doc.autoTable({
        startY: y + 2,
        head: headers,
        body: tableRows,
        styles: { fontSize: 8, cellPadding: 1.5, overflow: 'linebreak' },
        headStyles: { fillColor: [99, 102, 241], textColor: 255, fontStyle: 'bold' },
        alternateRowStyles: { fillColor: [248, 250, 252] },
        margin: { left: 14, right: 14 },
        columnStyles: colStyles,
      });

      setFooter(doc);
      doc.save(`manifest-${tripLabel}-${(tripName || '').replace(/\s+/g, '_').slice(0, 30)}.pdf`);
    } catch (e) {
      setError('Gagal generate manifest PDF: ' + (e?.message || 'unknown'));
    } finally {
      setPending(null);
    }
  }

  async function downloadRoomlist() {
    setPending('roomlist');
    setError('');
    try {
      const jspdf = await loadJsPDF();
      if (!jspdf) throw new Error('jsPDF gak ke-load');
      const { jsPDF } = jspdf;
      const doc = new jsPDF({ unit: 'mm', format: 'a4' });
      const customers = passengers.map((p) => p.customers).filter(Boolean);
      const roomsGen = generateRoomlist(passengers, customers);

      setHeader(doc, 'ROOMLIST', trip);

      let y = 26;
      doc.setFontSize(16);
      doc.setFont(undefined, 'bold');
      doc.text(`${tripName}`, 14, y);
      y += 6;
      doc.setFontSize(10);
      doc.setFont(undefined, 'normal');
      doc.text(`Kode: ${tripLabel}  ·  Berangkat: ${fmtDateID(departure)}${arrival ? `  ·  Pulang: ${fmtDateID(arrival)}` : ''}`, 14, y);
      y += 4;

      // Roomlist SAMA dengan proyeksi income ops (generateRoomlist auto live) — per kamar
      doc.text(`Total: ${passengers.length} pax · ${roomsGen.length} kamar`, 14, y);
      y += 2;

      for (const r of roomsGen) {
        const label = `Kamar ${r.room_no} · ${(r.room_type || '').toUpperCase()}${r.is_family ? ' (Family)' : r.gender === 'M' ? ' (Cowok)' : r.gender === 'F' ? ' (Cewek)' : ''}`;
        const headers = [['#', 'Nama', 'Gender', 'Phone', 'Catatan']];
        const tableRows = (r.pax || []).map((px, idx) => {
          const c = px.customers || {};
          const g = normalizeGender({ ...px, gender: c.gender || c.sex });
          return [idx + 1, c.name || '-', g === 'M' ? 'L' : g === 'F' ? 'P' : '-', c.phone || c.whatsapp || '-', r.needs_upgrade ? (r.upgrade_note || '') : ''];
        });

        doc.autoTable({
          startY: y + 4,
          head: headers,
          body: tableRows,
          styles: { fontSize: 9, cellPadding: 2 },
          headStyles: { fillColor: [168, 85, 247], textColor: 255, fontStyle: 'bold' },
          alternateRowStyles: { fillColor: [250, 245, 255] },
          margin: { left: 14, right: 14 },
          didDrawPage: (data) => {
            doc.setFontSize(11);
            doc.setFont(undefined, 'bold');
            doc.setTextColor(126, 34, 206);
            doc.text(`🛏 ${label} (${(r.pax || []).length})`, 14, data.cursor.y - 6);
            doc.setTextColor(30);
          },
          columnStyles: {
            0: { cellWidth: 10 },
            1: { cellWidth: 70 },
            2: { cellWidth: 20 },
            3: { cellWidth: 35 },
            4: { cellWidth: 45 },
          },
        });
        y = doc.lastAutoTable.finalY + 4;
      }

      setFooter(doc);
      doc.save(`roomlist-${tripLabel}-${(tripName || '').replace(/\s+/g, '_').slice(0, 30)}.pdf`);
    } catch (e) {
      setError('Gagal generate roomlist PDF: ' + (e?.message || 'unknown'));
    } finally {
      setPending(null);
    }
  }

  return (
    <div className="space-y-2">
      <div className="flex flex-wrap gap-2">
        <button
          type="button"
          onClick={downloadManifest}
          disabled={!!pending || passengers.length === 0}
          className="px-4 py-2 bg-red-500 hover:bg-red-600 disabled:opacity-50 text-white text-sm font-semibold rounded-lg flex items-center gap-2"
          title={passengers.length === 0 ? 'Belum ada peserta' : 'Download Manifest PDF'}
        >
          {pending === 'manifest' ? '⏳ Generating...' : '📄 Download Manifest (PDF)'}
        </button>
        <button
          type="button"
          onClick={downloadRoomlist}
          disabled={!!pending || passengers.length === 0}
          className="px-4 py-2 bg-pink-500 hover:bg-pink-600 disabled:opacity-50 text-white text-sm font-semibold rounded-lg flex items-center gap-2"
          title={passengers.length === 0 ? 'Belum ada peserta' : 'Download Roomlist PDF'}
        >
          {pending === 'roomlist' ? '⏳ Generating...' : '🛏 Download Roomlist (PDF)'}
        </button>
      </div>
      {error && (
        <p className="text-xs text-red-600 bg-red-50 border border-red-200 rounded p-2">⚠ {error}</p>
      )}
    </div>
  );
}
